Financial-Times/o-table

README.md
demos/src/basic.mustache
demos/src/captions.mustache
demos/src/modifiers.mustache
main.scss
src/scss/_base.scss
src/scss/_cells.scss
src/scss/_deprecated.scss
src/scss/_mixins.scss

This removes the styling based on the `o-table-data-type="numeric"` selector, however as this data attr is used for the JS sorting functionality it needs to remain so we're adding both the class and the data attr when the style is required. Not sure if this is the best way of doing this so leaving it open for discussion.
Would be a breaking change as well as we're requiring people to add a class to style the cells.

Move numeric styling from data attr to class

---

bower.json

When bower installing o-table, it is unable to find a suitable version for o-typography. With this update it will resolve its version to 4.3.1, which matches with other module requirements.

bower.json updated

---

src/js/oTable.js

`tbody > tr` contains hidden `th` elements which are shown on mobile. As the body rows contain these hidden table headers, the index used for sorting is not correct. We can fix this with a more specific selector. 
See: `/demos/local/responsive-flat.html`.

Correct sort behaviour for responsive tables.

---

src/js/oTable.js

Clicking a column to sort orders the column items ascending. However clicking a different, unsorted column will then order descending. 
This PR changes that behaviour so the first click of an unsorted column always orders ascending first.
The impact of this change is best demonstrated with some sort icons.
Sort order affordance is a work in progress, **this PR does not include the icons**, they are used to demonstrate the sort behaviour change.
Old: When sorting by "cost" for the first time it is ordered descending, after having just ordered "cheese" ascending.
New: When sorting by "cost" for the first time it is ordered ascending, same as when sorting "cheese" for the first time.

Always order table columns ASC on first click.

---

demos/src/basic.mustache
demos/src/captions.mustache
demos/src/pa11y.mustache
demos/src/responsive-flat.mustache
demos/src/responsive-overflow.mustache
demos/src/responsive-scroll.mustache
src/scss/_responsive-flat.scss
src/scss/_responsive-scroll.scss

Numeric columns `data-o-table-data-type="numeric"`, which contain numerical rows with the class `.o-table__cell--numeric` do not display correctly responsively.
Changes:
- On small screens align numerical cells left in responsive tables.
- Update the demos to include numerical column examples.
As well as adding new numerical column demos, `data-o-table-data-type="numeric"` has been removed from `td` cells in the demos. This doesn't appear to be needed, we only need to know that a column `th` is numeric to maintain sort functionality. Adding the `data-o-table-data-type` attribute arbitrarily could significantly increase the payload of a table with many numerical fields, but there may be a reason for it I'm missing.
before:
after:

Correct text alignment for number columns in responsive tables.

---

src/js/oTable.js

Table sorting appears to be broken in IE:
It seems IE loses the content of the table rows when `tbody.innerHTML = '';` is called, resulting in empty table row tags upon sort. As the `Node.appendChild()` method moves dom nodes from their current position to the new position if they already exist we can remove `tbody.innerHTML = '';` to fix this issue.
https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

Fix table sorting for IE.

---

bower.json
main.scss
src/scss/_base.scss
src/scss/_cells.scss
src/scss/_mixins.scss

Adds sort affordance to tables: We have a cursor pointer, an indication icon, and a hover state. 🎉 
@olipowell and I chatted through the changes, we think this style is a good way to improve `o-tables` in the short term.
So the sort icons can stay inline with the header, we have made changes to the style of `o-tables__cell--content-secondary`. It is no longer set to `display:block` and therefore sits inline when used in a table heading. We now ensure it's of normal weight to visually differentiate it.
**Before:**
**After:**

Sort affordance

---

demos/src/basic.mustache
demos/src/pa11y.mustache
src/js/oTable.js
src/scss/_base.scss
test/oTableSort.test.js

- Fix broken sort: Support sort on non numeric (i.e. empty) cells in numeric columns.
- Add an icon in empty cells. This provides a better screen reading experience as apposed to adding "-" to indicate a blank cell. The arbitrary size / weight is questionable though (review required). 
- Remove the content of some cells in the demo to show off the improved appearance and sort functionality.
Where it will be used (instead of dashes):

Add support for sorting numeric columns with blank cells.

---

src/js/oTable.js
test/oTableSort.test.js

This does not handle potential formats outside of the UK/US: 
"[...] while the U.K. and U.S. use a comma to separate groups of thousands, many other countries use a period instead, and some countries separate thousands groups with a thin space. Table 1-3 shows some commonly used numeric formats."
https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

Support comma separator for groups of thousands in numerical sort.

---

README.md
src/js/oTable.js
src/scss/_base.scss
test/oTableSort.test.js

Add `data-o-table-heading-disable-sort` to a column heading to disable sort on that column heading. The sort interface will not display on that heading and it will not be clickable.
Addresses: https://github.com/Financial-Times/o-table/issues/80

Add the ability to disable sort on individual columns

---

src/js/oTable.js
test/oTableSort.test.js

Use [`Intl.Collator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator) if available, otherwise fallback to [`String.prototype.localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)
Closes https://github.com/Financial-Times/o-table/issues/84

Sort strings based on localised values

---

README.md
src/js/oTable.js
test/oTable.test.js
test/oTableSort.test.js

Addresses: https://github.com/Financial-Times/o-table/issues/86
**Update:** This PR overview lies, see the updated readme.
**Adds the following prototype methods:**
- `sorted(columnIndex, sort)`
- `updateSortAttributes(columnIndex, sort)`
The `sorted` method  enables a consumer to fire the sorted event after they have successfully updated the table with new, sorted data.
The `updateSortAttributes` method provides a consumer the ability to update aria attributes independently. This could be useful if a sort has failed after having updated attributes for immediate visual feedback.
**Updated events:**
- Fires a new event `oTable.sorting` to indicate the table is about to be sorted. This includes the `sort` (e.g. "ASC"), `columnIndex` (e.g. "0"), and `instance` (of `oTable`). This event can …

Add events to enable the interception of sort for a custom implementation.

---

demos/src/row-headings.mustache
main.scss
origami.json
src/scss/_brand.scss
src/scss/_mixins.scss
src/scss/_row-headings.scss
src/scss/_row-stripes.scss

It'd be good to get your help next week on the workflow for brands - All I've been able to do is generate a set of demos for master
Unrelated to this PR, The readme doesn't have a contributing/installing section either. Is the standard origami workflow deliberately not included in individual readmes? Could do with a link to the centralised docs if there are some (I notice there's been some additions of docs in the registry recently, but nothing on contributing as yet, unless I've missed it)

2 column tables for internal brand

---

README.md
bower.json
demos/src/base.mustache
demos/src/basic.mustache
demos/src/expanding.mustache
demos/src/row-headings.mustache
demos/src/sorting.mustache
origami.json
src/js/Tables/BaseTable.js
src/js/Tables/OverflowTable.js
src/scss/_base.scss
src/scss/_brand.scss
src/scss/_wrapper.scss
test/OverflowTable.test.js
test/Sort/TableSorter.test.js
test/helpers/fixtures.js

- Add a footnote helper class.
- Adds an 'overlay wrapper' and renames the current wrapper to a 'scroll wrapper', which allows content to be placed below an expandable table but within the table container. 
- Also updates o-brand and wraps the called to oBrandDefine in a conditional.
Disliking the number of wrappers. Suggestions welcome. 😞

Add tfoot helper class and an overlay wrapper.

---

README.md
origami.json
src/js/Tables/BasicTable.js
src/js/oTable.js
src/scss/_base.scss
test/BasicTable.test.js
test/oTable.test.js

1. Adds a `BasicTable` class so `OverflowTable` is not the default.
2. Hide [a demo](http://localhost:8080/components/o-table@7.0.0-beta.1/#demo-expanding-table-with-arrow-dock) which is useful for dev but doesn't add much for users in the registry.
3. Fixes a specificity issue which cased footnotes to display incorrectly when within the table.
Before:
After:

Caption default table

---

src/scss/_base.scss
src/scss/_brand.scss
src/scss/_responsive-flat.scss
src/scss/_responsive-scroll.scss
src/scss/_row-headings.scss

Spot the difference! Update approved by Caroline.
Before:
Headers: black-90
Data: black-70
Normal body copy: black-80
After:
Headers: black-80
Data: black-80
Normal body copy: black-80

Reduce colours and brand variables.

---

src/scss/_base.scss

Before:
After:
If only character alignment was also available: 
https://drafts.csswg.org/css-text-4/#character-alignment

Enable tabular (monospaced) figures.

---

demos/src/cell-styles.mustache
origami.json
src/js/Tables/BaseTable.js
src/scss/_brand.scss
src/scss/_responsive-flat.scss
src/scss/_sort.scss

Tweaks alignment of sort buttons with right aligned content (before/after).
Updates flat table (before/after):

Flat table design updates.

---

README.md
demos/src/pa11y.mustache
main.scss
origami.json
src/js/Sort/CellFormatter.js
src/scss/_base.scss
src/scss/_borders.scss
src/scss/_compact.scss
src/scss/_container.scss
src/scss/_lines.scss
src/scss/_mixins.scss
src/scss/_responsive-flat.scss
src/scss/_responsive-overflow.scss
src/scss/_responsive-scroll.scss
src/scss/_row-headings.scss
src/scss/_row-stripes.scss
src/scss/_sort.scss
src/scss/_wrapper.scss
src/scss/variables.scss

- Make all mixins except `oTable` private -- accepts a feature flags in an `$opts` argument.
- Removes the default bottom margin, so the margin can be added or not according to the context of the table.
- Update the pa11y demo.
- Update the cell formatter to avoid the "Array.prototype.findIndex" polyfill.
Please review the readme carefully to make sure it all makes sense. :D

Final `o-table` changes.

---

bower.json
src/js/Tables/BaseTable.js

So there is only one listener for all column sort buttons.
There are still individual event listeners for controls in the table (optional) wrapper, but they won't increase with the number of columns.

Use dom-delegate for column sort buttons.

---

src/scss/_wrapper.scss

Notably improves performance in Chrome.

Remove misused "scroll-snap-type".

---

src/scss/_container.scss
src/scss/_mixins.scss

The "overflow" responsive table has a bottom margin on its container when expanding is enabled. This is a bug, the margin should have been applied to the table within to ensure the "show more / show fewer" button doesn't obscure table data.
Fixes: https://github.com/Financial-Times/o-table/issues/124

Prevent expanded table button obscuring table content.

---

README.md

Responsive-overflow and responsive-flat are mutually exclusive so we shouldn't apply both classnames at the same time in the same table.

doc: remove mutually exclusive classnames

---

demos/src/sorting.mustache
src/js/Tables/BaseTable.js
test/BaseTable.test.js
test/helpers/fixtures.js

o-table takes text content from column headings and puts it within a sort button. However this removes elements like `abbr` which should be maintained. More details here: https://github.com/Financial-Times/o-table/issues/132
This PR maintains a whitelist of child elements to keep when creating the sort button. All elements within the whitelist are valid within a button. That is [phrasing content](https://html.spec.whatwg.org/#phrasing-content-2) which is not [interactive content](https://html.spec.whatwg.org/#interactive-content-2). With some exceptions, which either don't feel relevant for a table heading or require more thought (mark, slots, autonomous custom elements) -- we might want to allow them in the future.

Support non-interactive, phrasing content in column sort buttons.

---

src/js/oTable.js

Mixing CJS and ESM was causing Webpack issues, with the latter saying `module.exports` is immutable. It may be a new thing in modern Webpack.
N.b., I haven't tested this with OBT but my feeling is that it shouldn't be breaking given oTable.js is imported via its `default` export in `main.js`.
Additionally: is there any appetite to get rid of [`babel-plugin-add-module-exports`](https://github.com/59naga/babel-plugin-add-module-exports) in OBT, which is unsupported and encourages non-standard module use? Making Webpack/Babel behaviour more prosaic would help facilitate implementing Origami outside the Build Service, such as we frequently do on IG. Could probably be done as a non-breaking change in most modules, happy to help.

Changes weird mix of CJS and ESM to just ESM

---

src/js/Sort/CellFormatter.js
src/js/Sort/TableSorter.js
src/js/Tables/BaseTable.js
src/js/Tables/OverflowTable.js
src/scss/_base.scss
src/scss/_sort.scss

- Only clone table cells for formatting if they haven't already been formatted.
- Sort is only called once per click (bug).
- Update the order of multiple rows at once with `prepend` rather than `appendChild` (where supported).
- Batches row updates on sort with `requestAnimationFrame`, for more immediate feedback and to break up rendering into multiple frames.
- Updates icon styles to avoid resizing the table when they're added.
- Removes styles which intended to give immediate feedback on click of the sort button, by immediately updating the sort icon. These were broken. When fixed I found it was more confusing to see an icon that indicated the table had been sorted even when it hadn't yet. We could introduce a loading state but my hope it with sort performance improvements we can avoid …

Improve sort and expander performance.

---

demos/src/huge.mustache
origami.json
src/js/Sort/TableSorter.js
src/js/Tables/BaseTable.js
src/js/Tables/OverflowTable.js

In a [previous PR](https://github.com/Financial-Times/o-table/pull/138), we rendered sorted table rows in batches to improve persevered performance. This works great when an expandable table is contracted as only those rows which are visible are updated immediately. However `o-table` does not currently account for when the table is expanded, in which case the user can see the rows as they update.
So:
- If the table is expandable and is currently contracted, on sort render the visible batch of rows first. Then render the rest.
- Otherwise, on sort render all sorted rows at once.
I've added a hidden demo with many rows to preview `o-table` with a large set of data.

Render expandable table in no more than two batches.

---

demos/src/huge.mustache
src/js/Sort/TableSorter.js
src/js/Tables/BaseTable.js
src/js/Tables/BasicTable.js
src/js/Tables/FlatTable.js
src/js/Tables/OverflowTable.js
src/js/Tables/ScrollTable.js
src/scss/_responsive-flat.scss
test/FlatTable.test.js
test/OverflowTable.test.js
test/ScrollTable.test.js

- Makes better use of window.requestAnimationFrame to prevent forced reflows.
- Moves the table row render function so rows may be hidden in one place ([ready for the filter feature](https://github.com/Financial-Times/o-table/pull/150)).
This shows the Chrome Dev Tools performance profile of the "huge" table demo on load, with cpu throttled x6. The demo has 1000 rows, 10 columns, sortable headings, and an expander. The render time is much less thanks to avoiding some forced reflows  (before / after):

Improve table render performance.

---

src/js/Tables/BaseTable.js
src/js/Tables/OverflowTable.js
src/scss/_base.scss

- When a table is contracted, half of one hidden row is visually shown behind a fade out to indicate expandability.
- When a contracted table is sorted its height does not change. However if the rows now at the top of the table are less tall, some "hidden" rows may become visually visible.
- We do not update the contracted table height to avoid the table causing the rest of the page to re-render. Unless the max table height becomes smaller than the current contracted table height upon filter.

Only visually hide filtered and update the contracted table height if needed

---

README.md
demos/src/huge.mustache
src/js/Tables/BaseTable.js
src/js/Tables/OverflowTable.js
src/js/Tables/ScrollTable.js
src/scss/_base.scss
src/scss/_responsive-flat.scss
test/BaseTable.test.js
test/OverflowTable.test.js

This is due to inconsistent browser support. For example Safari treated "visibility: collapsed" as "visibility: hidden", which caused large blank tables. Now a height is set on the table container to hide filtered rows with overflow. "display: none" can't be used as this would cause column widths to be recalculated.

Remove use of "visibility: collapsed" to hide filtered rows.

---

bower.json
src/js/Tables/BaseTable.js

v3 of ftdomdelegate has the same api as v2. It was named
dom-delegate in its manifest files and v3 makes the name
consistent. It was also released (renamed) as 2.2.0 on npm.
https://github.com/Financial-Times/ftdomdelegate/pull/93

Allow version 2 or 3 of ftdomdelegate. 

---

demos/src/base.mustache
demos/src/demo.scss
demos/src/huge.mustache
origami.json

Will maybe create an issue to propose adding a field modifer to o-forms
to contain the width of a field. I've had to write custom CSS here and
when adding v6 to https://github.com/Financial-Times/tech.in.ft.com.
Before: Unwanted padding to the left, unwanted space after the label.
Now: Beautiful 🎉 (but with some custom css to constrain the width)

Update demo to o-forms@^7.0.0 :tada:

---

MIGRATION.md
bower.json
main.scss
src/scss/_base.scss
src/scss/_variables.scss

Replace o-typography spacing Sass which will be deprecated.
This is not considered a breaking change as o-spacing is a
new component.
This PR also moves the global silient mode variable to a
`variables.scss` file for consistency with other components.

Introduce o-spacing.

---

bower.json

See:
- https://github.com/Financial-Times/o-table/pull/172
- https://github.com/Financial-Times/o-icons/pull/98

o-table fails to build for any version of o-icons below 4.5.1.

---

.circleci/config.yml
MIGRATION.md
README.md
bower.json
demos/src/demo.scss
origami.json
package-lock.json
package.json
src/scss/_base.scss
src/scss/_brand.scss
src/scss/_compact.scss
src/scss/_responsive-overflow.scss
src/scss/_sort.scss

(closes #166)
I've removed the deprecated margin class, updated the dependencies to use :carrot: ranges and that seems to be it.
There are no public mixins other than the primary, the JS is already esm. Do we want to break o-table some more?

Break o-table

---

README.md
demos/src/pa11y.mustache
src/js/Tables/FlatTable.js
src/scss/_responsive-flat.scss
test/BaseTable.test.js
test/FlatTable.test.js

Updates the responsive flat table to have valid html. It is no longer announced 
as an empty table to screen reader users. To achieve the visual look each row
becomes a new `tbody`, with a row for each data cell and its corresponding header.
Addresses: https://github.com/Financial-Times/o-table/issues/180
This:
```html
<table>
<thead>
<th>h</th>
</thead>
<tbody>
<tr>
<td>a</td>
</tr>
<tr>
<td>b</td>
</tr>
</tbody>
</table>
```
Becomes this for the flat view:
```html
<table>
<tbody>
<tr>
<th>h</th>
<td>a</td>
</tr>
</tbody>
<tbody>
<tr>
<th>h</th>
<td>b</td>
</tr>
</tbody>
</table>
```

Add flat and scroll variants to the pa11y demo

---

demos/src/demo.js
main.js
test/BaseTable.test.js
test/BasicTable.test.js
test/FlatTable.test.js
test/OverflowTable.test.js
test/ScrollTable.test.js
test/Sort/TableSorter.test.js
test/oTable.test.js

Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.

Stop using magic webpack imports

---

README.md
src/js/Tables/BaseTable.js
src/js/oTable.js
test/BaseTable.test.js

When a sortable table heading is clicked for the first time
an ascending sort is applied by default, assuming no existing
sort i.e. a server side sort. However for some usecases a
descending sort is more helpful. A new
`data-o-table-preferred-sort-order` option allows the default
sort to be configured.
https://github.com/Financial-Times/o-table/issues/208

Add option `data-o-table-preferred-sort-order`

---

src/js/Tables/BaseTable.js
src/scss/_sort.scss
test/BaseTable.test.js

- Express the sort order in the title of the sort button for
screen reader users. E.g. instead of `sort table by "name"`
use a title of `sort table by "name" ascending`.
- If the preferred sort order has been set, show the correct
sort icon on hover.
Relates to:
https://github.com/Financial-Times/o-table/issues/208
https://github.com/Financial-Times/o-table/pull/210

Improve table sort order buttons.

---

demos/src/demo.js
main.js
src/js/Sort/TableSorter.js
src/js/Tables/BasicTable.js
src/js/Tables/FlatTable.js
src/js/Tables/OverflowTable.js
src/js/Tables/ScrollTable.js
src/js/oTable.js
test/BaseTable.test.js
test/BasicTable.test.js
test/FlatTable.test.js
test/OverflowTable.test.js
test/ScrollTable.test.js
test/Sort/TableSorter.test.js
test/oTable.test.js

relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing

add extension to relative imports to make the code work directly in a browser

---

package.json

This project used to support heroku review apps but lost that support when the npm-run scripts were deleted.
This commit adds the required npm-run scripts which enable heroku review apps to work once more.

Enable heroku review apps to work once again

---

.github/workflows/add-new-issues-and-pull-requests-to-origami-project-board.yml
.github/workflows/apply-labels.yml
.github/workflows/auto-approve.yml
.github/workflows/sync-repo-labels.yml
package.json

We have workflows that currently fail to run correctly for pull-requests from forks or pull-requests from dependabot. The reason is because those workflows are being triggered by the 'pull_request' event, which does will use a restricted github api token for pull-requests from forks or dependabot for security reasons.
For our workflows which are 'safe' (meaning they do not checkout the code or execute the code in the repository), we can change their trigger from 'pull_request' to 'pull_request_target', which uses a github api token with more permissions, specifically it has permission to read/use secrets, which are the things are workflows require.
Our workflows are safe, they do not checkout or execute the code from the repository, so we should change to using `pull_request_target` to …

use pull_request_target and not pull_request for the safe workflows

---

src/js/Tables/BaseTable.js
test/BaseTable.test.js

The `updateRows` method previously only re-applied an existing sort
and filter if new rows were added. Now sort and filters are
always re-applied to account for rows which have been removed
and also rows which have modified cells.

Update the `updateRows` method to account for removed or changed rows.

---

demos/src/base.mustache
origami.json
src/js/Tables/BaseTable.js

Supports the "overflow" responsive table but has not been tested
with other styles of table.
See related issue: https://github.com/Financial-Times/o-table/issues/255

Allow multiple header rows
