Financial-Times/o-table

- src/js/oTable.js
Tests will be added after #42 is merged.
Fixes #41
> Fix JS and table breaking when no thead element

- README.md
- src/js/oTable.js
- test/oTableSort.test.js
So you can e.g. have a name and summary column which sorts by name
> custom sort alphabetically

- src/scss/_borders.scss
> Update linting exclusion from scss-lint to sass-lint.

- origami.json
- src/js/oTable.js
- test/oTable.test.js
- Add o-normalise as a demos dependency
- Make sortable heading keyboard interactable
> Focus style

- README.md
- demos/src/basic.mustache
- demos/src/captions.mustache
- demos/src/pa11y.mustache
- demos/src/responsive-flat.mustache
- demos/src/responsive-overflow.mustache
- demos/src/responsive-scroll.mustache
- src/js/oTable.js
- test/oTableSort.test.js
> fix query for sorting

- README.md
- demos/src/basic.mustache
- demos/src/pa11y.mustache
- demos/src/responsive-flat.mustache
- demos/src/responsive-overflow.mustache
- demos/src/responsive-scroll.mustache
- test/oTableSort.test.js
Addresses https://github.com/Financial-Times/o-table/issues/78
> Correct demo markup.

- src/scss/_row-headings.scss
Reverts Financial-Times/o-table#96
Aaargh - broken
> Revert "Prevent row headings applying to nested tables"

- README.md
- demos/src/cell-styles.mustache
- origami.json
- src/scss/_cells.scss
- src/scss/_mixins.scss
> Add class to vertically centre cell contents

- src/scss/_responsive-flat.scss
Flat table wasn't given much TLC. This does some tidy up ready for any changes needed for an upcoming design update.
> Tidy up flat table ready for design changes.

- src/scss/_responsive-overflow.scss
The new version of OBT revealed a build failure for the whitelabel brand. This fixes that 🎉 
What does a whitelabel table look like you cry?
> Fix for the whitelabel brand.

- MIGRATION.md
- README.md
does what it says on the tin ☝️ so that we can start getting migration.mds around our components and make moar consistency  💪
> Readme migration

- README.md
> Fix minor readme typo

- MIGRATION.md
- README.md
- src/scss/_base.scss
Also removes the silent mode reference in the readme.
> Add bottom margin spacing class.

- src/js/Tables/BaseTable.js
- src/js/Tables/OverflowTable.js
- src/js/Tables/ScrollTable.js
- IE11 does not fire input events on select inputs.
- IE11 does not support Array.prototype.includes
> Fix for IE11.

- MIGRATION.md
- src/scss/_base.scss
> Remove deprecated `.o-table-margin-bottom`

- MIGRATION.md
- bower.json
> Remove `>=` ranges from `bower.json`

- README.md
Relates to https://github.com/Financial-Times/o-table/issues/177
> Reference Sass options in markup documentation for responsive features.

- src/js/Tables/BaseTable.js
Previously this only happened if a filter had been set.
> Always update table container height on browser resize.

- src/scss/_responsive-overflow.scss
So content behind a hidden table control may be interacted with.
> Prevent pointer events on hidden controls.

- demos/src/sorting-disabled.mustache
- origami.json
- test/BasicTable.test.js
- test/FlatTable.test.js
- test/OverflowTable.test.js
- test/ScrollTable.test.js
Closes https://github.com/Financial-Times/o-table/issues/147
> Add tests and demo to show sorting can be disabled

- .github/workflows/percy.yml
If this looks good, I will add it to all our components
> only run percy when a file has changed which can affect a demo

- .github/workflows/add-new-issues-and-pull-requests-to-origami-project-board.yml
- .github/workflows/apply-labels.yml
- .github/workflows/sync-repo-labels.yml
origami discussion for this work -- https://github.com/Financial-Times/origami/issues/77
> make forks run workflows correctly by using pull_request_target

- test/OverflowTable.test.js
without this change, if a test fails, mocha will incorrectly report it as a timeout and not show the assertion error
> place error into `done` callback to let mocha know a test failed instead of timed out
